### ISSUE TITLE
Lost package qualifier on function call

### ISSUE THREAD

**Issue by pwaller** [dave/dst#34]
Thanks for starting this package, the problem it solves is one I encountered a very long time ago!

I just started off with a very simple test:

```go
package b

func B() {
	println("B")
}
```

```go
package a

import "github.com/pwaller/example/testdata/a/b"

func A() {
	b.B()
}
```

With the following program I get unexpected output:

```go
package main

import (
	"golang.org/x/tools/go/packages"

	"github.com/dave/dst/decorator"
)

func main() {
	pkgs, err := decorator.Load(&packages.Config{Mode: packages.LoadAllSyntax}, ".")
	if err != nil {
		panic(err)
	}

	for _, p := range pkgs {
		for _, s := range p.Syntax {
			decorator.Print(s)
		}
	}
}
```

Here is the output:

```go
package a

import "github.com/pwaller/example/testdata/a/b"

func A() {
	B()
}
```

I expected that I should see a call to `b.B()`, not `B()`, so it seems the package qualifier is lost.

This is using `github.com/dave/dst v0.23.0`.

I'm a bit surprised by the bug, I would have thought this case should work - have I done something wrong? Thanks!

**Comment by pwaller** [comment]
I found the notes about restoring qualifiers in the readme more or less immediately after hitting comment. Sorry for the noise :).

https://github.com/dave/dst#imports

**Comment by dave** [comment]
Yes, the problem is that `decorator.Load` resolves the imports and converts `*SelectorExpr` that correspond to qualified ident into `*Ident` with the `Path` property set. The default implementation of `decorator.Print` doesn't have a package name resolver, so it's leaving the node as an `*Ident`. 

I think the restorer should panic if it encounters a `*Ident` with non-empty `Path` and no restorer set... I don't think there's any possibility that this would be intentional. I'm going to re-open this and see if I can get it to panic in this situation.

**Comment by dave** [comment]
Does this error message make sense to you?

"This syntax has been decorated with import management enabled, but the restorer does not have import management enabled. Use NewRestorerWithImports to create a restorer with import management. See the Imports section of the readme for more information."

**Comment by pwaller** [comment]
Looks good to me!

**Comment by dave** [comment]
OK can you give it a try with `v0.23.1` and double check it panics with the first code?

**Comment by pwaller** [comment]
Confirmed:
```
panic: This syntax has been decorated with import management enabled, but the restorer does not have import management enabled. Use NewRestorerWithImports to create a restorer with import management. See the Imports section of the readme for more information.

goroutine 1 [running]:
github.com/dave/dst/decorator.(*FileRestorer).restoreIdent(0xc0001b6900, 0xc0000fc600, 0x747186, 0x8, 0x746338, 0x3, 0x746513, 0x4, 0xc0000df700, 0xc000102480, ...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer.go:490 +0xbe4
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc0001b6900, 0x7b10c0, 0xc0000fc600, 0x747186, 0x8, 0x746338, 0x3, 0x746513, 0x4, 0x462f0aabc3e2c900, ...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer-generated.go:970 +0xf632
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc0001b6900, 0x7b0e60, 0xc0001b20c0, 0x7471ce, 0x8, 0x746169, 0x1, 0x746513, 0x4, 0x7f56b2dbdd00, ...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer-generated.go:271 +0x88df
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc0001b6900, 0x7b0f80, 0xc0001965f0, 0x747598, 0x9, 0x74653f, 0x4, 0x746577, 0x4, 0x0, ...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer-generated.go:590 +0x4314
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc0001b6900, 0x7b0e20, 0xc0001c0070, 0x7471e6, 0x8, 0x7464df, 0x4, 0x747598, 0x9, 0x0, ...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer-generated.go:221 +0x52f0
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc0001b6900, 0x7b1020, 0xc0001c2000, 0x746517, 0x4, 0x746769, 0x5, 0x746507, 0x4, 0x414600, ...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer-generated.go:828 +0xe080
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc0001b6900, 0x7b0fe0, 0xc000198b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer-generated.go:690 +0x9304
github.com/dave/dst/decorator.(*FileRestorer).RestoreFile(0xc0001b6900, 0xc000198b60, 0xc00019c100, 0x39, 0x40)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer.go:140 +0x21d
github.com/dave/dst/decorator.(*Restorer).RestoreFile(...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/restorer.go:65
github.com/dave/dst/decorator.RestoreFile(0xc000198b60, 0xc00009e000, 0x2, 0xc000100060, 0x25)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/helpers.go:59 +0x1af
github.com/dave/dst/decorator.Fprint(0x7b1520, 0xc00000e018, 0xc000198b60, 0xc0000f0ec0, 0xc0000fa0e0)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/helpers.go:49 +0x2f
github.com/dave/dst/decorator.Print(...)
	/home/pwaller/.local/pkg/mod/github.com/dave/dst@v0.23.1/decorator/helpers.go:44
main.main()
	/home/pwaller/.local/src/github.com/pwaller/glom/main.go:25 +0x1af
```
