### ISSUE TITLE
Duplicate node restoring new function

### ISSUE THREAD

**Issue by myshkin5** [dave/dst#49]
I'm trying to generate code similar to this:

```go
type something struct {
	here int
}

func newSomething() *something {
	return &something{
		here: 42,
	}
}
```

I've got the struct in place and a start on the func but the body of the func is giving me an error:

```
panic: duplicate node: &dst.Ident{Name:"something", Obj:(*dst.Object)(nil), Path:"", Decs:dst.IdentDecorations{NodeDecs:dst.NodeDecs{Before:0, Start:dst.Decorations(nil), End:dst.Decorations(nil), After:0}, X:dst.Decorations(nil)}}

goroutine 1 [running]:
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc000626e10, 0x1457e60, 0xc000625a80, 0x13dd1ff, 0xc, 0x13db130, 0x4, 0x13db0c0, 0x4, 0x0, ...)
	/Users/dschultz/workspace/go/pkg/mod/github.com/dave/dst@v0.25.5/decorator/restorer-generated.go:15 +0x14356
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc000626e10, 0x1457c80, 0xc000559c20, 0x13dc48c, 0x9, 0x13dacc7, 0x1, 0x13db0c0, 0x4, 0x0, ...)
	/Users/dschultz/workspace/go/pkg/mod/github.com/dave/dst@v0.25.5/decorator/restorer-generated.go:459 +0x7fe
github.com/dave/dst/decorator.(*FileRestorer).restoreNode(0xc000626e10, 0x1458140, 0xc000619730, 0x13dc8fe, 0xa, 0x13dbaef, 0x7, 0x13db0c0, 0x4, 0x0, ...)
	/Users/dschultz/workspace/go/pkg/mod/github.com/dave/dst@v0.25.5/decorator/restorer-generated.go:1839 +0x1b0d
```

I dumped the DST of a go file similar to what I want to create:

```
  1280  .  .  .  Body: *dst.BlockStmt {
  1281  .  .  .  .  List: []dst.Stmt (len = 1) {
  1282  .  .  .  .  .  0: *dst.ReturnStmt {
  1283  .  .  .  .  .  .  Results: []dst.Expr (len = 1) {
  1284  .  .  .  .  .  .  .  0: *dst.UnaryExpr {
  1285  .  .  .  .  .  .  .  .  Op: &
  1286  .  .  .  .  .  .  .  .  X: *dst.CompositeLit {
  1287  .  .  .  .  .  .  .  .  .  Type: *dst.Ident {
  1288  .  .  .  .  .  .  .  .  .  .  Name: "something"
  1289  .  .  .  .  .  .  .  .  .  .  Obj: *(obj @ 50)
  1290  .  .  .  .  .  .  .  .  .  .  Path: ""
```

My code is creating an identical structure but it looks like the restorer code thinks that `something` is duplicate when defined on line 1288 above. Also not sure what to do about the `Op` field. I'm setting it to `token.AND` but not sure if that's right.

Any help is greatly appreciated!

**Comment by myshkin5** [comment]
If I throw an `XX` at the end of the name on 1288 I get the following out of the restorer:

```go
type something struct {
	here int
}

func newSomething() *something {
	return &somethingXX{
		here: 42,
	}
}
```

It feels like I have the `Op` field right but there is something odd going on with the duplicate node check. And I can't turn the check off as `allowDuplicate` is set by `RestoreFile`.

**Comment by dave** [comment]
Can I see your code?

**Comment by dave** [comment]
Without seeing your code it's hard to work out what's going wrong, but generally that panic is encountered when you try to reuse the same node in two places in the tree. You definitely shouldn't do this, and to avoid it you can clone the node with the `dst.Clone` function.

**Comment by dave** [comment]
Glad you solved the problem!

**Comment by myshkin5** [comment]
If only I knew how

🤷

**Comment by myshkin5** [comment]
I reproduced this issue and yes, I was reusing a node. Evidently I shouldn't be reusing even the `*dst.Ident` objects (thought they were just names). When I replace the func decl above with the below snippet, I get the original error again:

```go
	ident := dst.NewIdent("something")
	file.Decls = append(file.Decls, &dst.FuncDecl{
		Name: dst.NewIdent("newSomething"),
		Type: &dst.FuncType{
			Params: &dst.FieldList{},
			Results: &dst.FieldList{
				List: []*dst.Field{
					{
						Type: &dst.StarExpr{
							X: ident,
						},
					},
				},
			},
		},
		Body: &dst.BlockStmt{
			List: []dst.Stmt{
				&dst.ReturnStmt{
					Results: []dst.Expr{
						&dst.UnaryExpr{
							Op: token.AND,
							X: &dst.CompositeLit{
								Type: ident,
							},
						},
					},
				},
			},
		},
	})
```
