### ISSUE TITLE
Panic when decorating code with a call to a generic function

### ISSUE THREAD

**Issue by chavacava** [dave/dst#77]
Hi, first of all, thanks for the very useful library! 
I'm using the library to do some code generation and I"ve hit a panic when trying to decorate code with a call on a generic function.
Here is an example of code triggering the panic:

(file `makes-dst-fail.go`)
```go
package main

import (
	"maps"
)

func main() {
	a := map[string]string{}
	b := map[string]string{}
	maps.Copy[map[string]string, map[string]string](b, a) // call to a generic function
}
```

when analyzing with 

```go
package main

import (
	"go/parser"
	"go/token"
	"os"

	"github.com/dave/dst/decorator"
)

func main() {
	input, err := os.Open("makes-dst-fail.go")
	if err != nil {
		panic(err)
	}
	defer input.Close()

	fset := token.NewFileSet()
	astFile, err := parser.ParseFile(fset, "", input, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	astDecorator := decorator.NewDecorator(fset)
	_, err = astDecorator.DecorateFile(astFile) // this call panics
	if err != nil {
		panic(err)
	}
}
```
I get
```
panic: interface conversion: interface is nil, not dst.Expr

goroutine 1 [running]:
github.com/dave/dst/decorator.(*fileDecorator).decorateNode(0xc000093d98, {0x5f7350, 0xc0000146c0}, {0x5b8714, 0x8}, {0x5f42e8, 0x1}, {0x5b7b4b, 0x4}, {0x5f7260, ...})
	/home/chavacava/go/pkg/mod/github.com/dave/dst@v0.23.1/decorator/decorator-node-generated.go:314 +0xfd65
github.com/dave/dst/decorator.(*fileDecorator).decorateNode(0xc000093d98, {0x5f6ef0, 0xc00013c120}, {0x5b8ac2, 0x9}, {0x5b7b4f, 0x4}, {0x5b7b53, 0x4}, {0x5f7350, ...})
	/home/chavacava/go/pkg/mod/github.com/dave/dst@v0.23.1/decorator/decorator-node-generated.go:662 +0x154b5
github.com/dave/dst/decorator.(*fileDecorator).decorateNode(0xc000093d98, {0x5f7080, 0xc00013c150}, {0x5b8724, 0x8}, {0x5b7adb, 0x4}, {0x5b8ac2, 0x9}, {0x5f6ef0, ...})
	/home/chavacava/go/pkg/mod/github.com/dave/dst@v0.23.1/decorator/decorator-node-generated.go:245 +0x122e5
github.com/dave/dst/decorator.(*fileDecorator).decorateNode(0xc000093d98, {0x5f7148, 0xc0001283c0}, {0x5b7ae3, 0x4}, {0x5b7d50, 0x5}, {0x5b7b5f, 0x4}, {0x5f7080, ...})
	/home/chavacava/go/pkg/mod/github.com/dave/dst@v0.23.1/decorator/decorator-node-generated.go:947 +0x6f94
github.com/dave/dst/decorator.(*fileDecorator).decorateNode(0xc000093d98, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x5f7148, ...})
	/home/chavacava/go/pkg/mod/github.com/dave/dst@v0.23.1/decorator/decorator-node-generated.go:784 +0x1353c
github.com/dave/dst/decorator.(*Decorator).DecorateNode(0xc000068f60, {0x5f7148, 0xc0001283c0})
	/home/chavacava/go/pkg/mod/github.com/dave/dst@v0.23.1/decorator/decorator.go:129 +0x165
github.com/dave/dst/decorator.(*Decorator).DecorateFile(0xc000106980?, 0x0?)
	/home/chavacava/go/pkg/mod/github.com/dave/dst@v0.23.1/decorator/decorator.go:104 +0x1d
main.main()
	/home/chavacava/workspace/sandbox/main.go:26 +0x1eb
exit status 2
```

Does `dst`  support working on code with generics? Or I'm not correctly using the library?

Thanks again

**Comment by myshkin5** [comment]
@chavacava I'm not a maintainer but I've used this library quite a bit. dst definitely supports generics and I'm generating lots of complicated code with it successfully. I'll go out on a limb here and say that since you are decorating valid Go, this is a bug in dst. IIRC Dave is taking a break on this library so if this is important to you, I would recommend trying to fix this yourself and submit a PR.

**Comment by chavacava** [comment]
HI @myshkin5 thank you for the feedback. I'll take a look and try to fix the bug.

**Comment by dave** [comment]
Hey really sorry I haven't had time to look into this! I will have a bit more time in the next few weeks so might be able to give it an hour or so... but if you can work out what the problem is, that would make my life easier!

**Comment by dave** [comment]
I'm just testing this and I don't seem to be able to get it to fail... Maybe in your example, the 'makes-dst-fail.go' file is different on your machine?

I've tweaked it to use a string, and I don't get the same error:

```go
package main

import (
	"go/parser"
	"go/token"

	"github.com/dave/dst/decorator"
)

func main() {
	code := `package main

import (
	"maps"
)

func main() {
	a := map[string]string{}
	b := map[string]string{}
	maps.Copy[map[string]string, map[string]string](b, a) // call to a generic function
}
`

	fset := token.NewFileSet()
	astFile, err := parser.ParseFile(fset, "", code, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	astDecorator := decorator.NewDecorator(fset)
	f, err := astDecorator.DecorateFile(astFile) // this call panics
	if err != nil {
		panic(err)
	}

	if err := decorator.Print(f); err != nil {
		panic(err)
	}

	//Output:
	//package main
	//
	//import (
	//	"maps"
	//)
	//
	//func main() {
	//	a := map[string]string{}
	//	b := map[string]string{}
	//	maps.Copy[map[string]string, map[string]string](b, a) // call to a generic function
	//}

}

```

**Comment by dave** [comment]
I'm going to close this issue for now, but feel free to re-open if I've misunderstood.

**Comment by chavacava** [comment]
Hi @dave, thanks for trying to reproduce the problem. I was amazed you can't reproduce the panic but after testing on other of my computers I'm not able to reproduce it. I'll try to put some time investigating why my code panics in my dev computer. (some dependency thing I suspect)
Thanks again, and sorry for the trouble.

**Comment by dave** [comment]
I just double checked with the latest Go version:

```
osx~/s/d/foo (master) $ go version
go version go1.23.5 darwin/arm64
osx~/s/d/foo (master) $ go run main.go
package main

import (
	"maps"
)

func main() {
	a := map[string]string{}
	b := map[string]string{}
	maps.Copy[map[string]string, map[string]string](b, a) // call to a generic function
}
```

**Comment by dave** [comment]
Let me know if you get to the bottom of why it's not working!
